SELECT 
    V1.COD_VENDEDOR
FROM 
    VENDAS V1
JOIN 
    VENDAS V2 ON V1.COD_VENDEDOR = V2.COD_VENDEDOR
WHERE 
    V1.COD_PRODUTO = 'PROD_1' AND V2.COD_PRODUTO = 'PROD_1'
    AND V1.DATA BETWEEN DATA_INICIO AND DATA_FIM
    AND V2.DATA BETWEEN DATA_INICIO AND DATA_FIM
    AND V1.DATA < V2.DATA
GROUP BY 
    V1.COD_VENDEDOR
HAVING 
    MIN(V2.QUANTIDADE - V1.QUANTIDADE) > 0;